# Generated by Django 2.2 on 2021-06-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='username',
        ),
    ]
