# Generated by Django 2.2 on 2021-06-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0004_auto_20210622_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(null=True)),
                ('MedicinePrescribed', models.TextField()),
                ('isActive', models.BooleanField(default=False)),
                ('Disease', models.CharField(max_length=100)),
                ('DatedON', models.DateTimeField(auto_now=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.Doctor')),
                ('HospitalName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.Hospital')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_data', to='HospitalApp.Patient')),
            ],
        ),
    ]
