# Generated by Django 2.2 on 2021-06-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0005_diseasedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedata',
            name='Doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diseasedata',
            name='HospitalName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diseasedata',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
