# Generated by Django 2.2 on 2021-08-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0010_auto_20210828_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='hospital/'),
        ),
    ]
