# Generated by Django 2.2 on 2021-09-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0012_hospital_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='timings',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='website',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
