# Generated by Django 2.2 on 2021-09-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0016_auto_20210911_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='linkedIn',
            new_name='linkedin',
        ),
    ]
